# Simple docker-composer.yml
# You can change your port or volume location

version: '3.3'
networks:
  app-tier:
    driver: bridge

services:
  db:
    image: 'bitnami/mariadb:latest'
    container_name: kumadb
    restart: on-failure
    environment:
      MARIADB_EXTRA_FLAGS: --max-connect-errors=1000 --max_allowed_packet=16M --max_connections=10 --query_cache_size=512K --thread_cache_size=0 --sort_buffer_size=32K --bulk_insert_buffer_size=0 --tmp_table_size=1K --max_heap_table_size=16K --key_buffer_size=1M --read_buffer_size=8K --read_rnd_buffer_size=8K --innodb_buffer_pool_size=10M --innodb_log_buffer_size=512K
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: kumadb
      MARIADB_USER: kumadb_user
      MARIADB_PASSWORD: kumadb_pass
      MARIADB_ROOT_HOST: '%'
    expose:
      - "3306"
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - app-tier
    volumes:
      - ${PWD}/data/mariadb:/bitnami/mariadb/data

  uptime-kuma:
    depends_on:
      - db
    image: uptime-kuma
    container_name: uptime-kuma
    restart: always
    environment:
      DB_MYSQL_HOST: kumadb
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: kumadb_user
      DB_MYSQL_PASSWORD: kumadb_pass
      DB_MYSQL_DBNAME: kumadb
      DB_DIALECT: mysql
    volumes:
      - ./uptime-kuma:/app/data
    ports:
      - "3001:3001"
    networks:
      - app-tier
